### ISSUE TITLE
Clean up some deprecation 

### ISSUE THREAD

**Issue by tautology0** [santoru/shcheck#17]
X-XSS-Protection is pretty much unsupported by any real browser (IIRC Internet Explorer, and *maybe* Safari) still honour it. And it is best implemented by a content security policy anyway, so can we remove it from the list.

Also X-Permitted-Cross-Domain-Policies, is default secure, if it doesn't exist then Flash/Air will go to a crossdomain.xml. If neither exist then Flash/Air will refuse to work. So it's probably best to be removed from the list too.

**Comment by tautology0** [comment]
Expect-CT will also be deprecated from June 2021

**Comment by santoru** [comment]
I added a way on https://github.com/santoru/shcheck/commit/bbbb99ba5489352864dbb28f5257cd70d2f3ff1d to mark headers as deprecated and to optionally display them (by default these will be hidden). What do you think? 
I'll mark `Expect-CT` as deprecated in June 2021.

**Comment by tautology0** [comment]
Look like a good idea to me - though you probably want to add Features-Policy back in as a deprecated header (as I still see it out in the wild).

X-Permitted-Cross-Domain-Policies is a difficult one as technically it is safer to just not have it (unless you require Flash permissions to be set). But putting it in deprecated is probably a good compromise.

**Comment by santoru** [comment]
Make sense, I could make some improvements to add additional validation if `X-Permitted-Cross-Domain-Policy` is present, but I think it will go out of scope for the tool. 
Thank you for the help!
