### ISSUE TITLE
Stops running on a list when a host is unreachable

### ISSUE THREAD

**Issue by Xitro01** [santoru/shcheck#21]
While using the "--hfile=" parameter and in the case that one host is not reachable, the tool will completely stop and not process the rest of the list. It would be great if it would just run through the whole list.
Maybe add a feature that makes the tool stop when something is unreachable.

Thanks in advance!

**Comment by santoru** [comment]
Hey @Xitro01, thank you for the bug report. I'll try to replicate it and provide a fix.

**Comment by santoru** [comment]
Hi @Xitro01, should be solved in bc438b6aeca901ad37fcfcd4932bffdb56ebbf5b
