### ISSUE TITLE
Option "-no-color" request

### ISSUE THREAD

**Issue by guillaumekaddouch** [santoru/shcheck#24]
Hello,

Your tool is great, and I would like to use it. However, when storing shcheck's output to a file, the colors are not visible but the color codes instead, which makes it very difficult to read. Most other tools I use have a "-no-color" switch which disables any colors, allowing to store raw output to files. That would be great to have such option.

Additionaly, having a label "[warn]", "[info]", or "[crit]" before each http header when disabling colors would be nice, but not required :-)

I hope you will see the benefits of these feature requests !

Regards,
Guillaume

**Comment by santoru** [comment]
Hello @guillaumekaddouch,
Thank you for your feedback.
You can already disable the colored output using `--colors=none`.
I will add this to the documentation as it is not yet documented :) thank you!
