### ISSUE TITLE
Update the response headers according to OWASP Secure Headers Project

### ISSUE THREAD

**Issue by manuel-sommer** [santoru/shcheck#28]
Hi there,

I recommend to update the checked headers according to the following project:
https://owasp.org/www-project-secure-headers/

The following HTTP Response header are deprecated according to this project: 
- [Expect-CT](https://owasp.org/www-project-secure-headers/#expect-ct)
- [X-XSS-Protection](https://owasp.org/www-project-secure-headers/#x-xss-protection)

Best Regards,

Manuel

**Comment by santoru** [comment]
Done in https://github.com/santoru/shcheck/pull/29, thanks!
